# Docker Compose override for development
version: '3.8'

services:
  backend:
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=hireiq_backend.settings
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  mongodb:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"
